### ISSUE TITLE
Create a python package

### ISSUE THREAD

**Issue by OpenBagTwo** [OpenBagTwo/AngerLocalBeehive#3]
**GIVEN** that some of my notebooks contain things I want to run regularly
**WHEN** I run `pip install anger-local-beehive` (or poetry install or conda?) into a virtual environment
**THEN** I have access to command-line utilities that allow me to perform the specific tasks that were prototyped in the notebooks
**SO** that I don't have to spin up Jupyter and run through a notebook every time I want to do that thing

### Some examples:
- Finding a specific mob [by species](https://github.com/OpenBagTwo/AngerLocalBeehive/blob/main/notebooks/Allays%20Went%20Away%3F.ipynb), [owner, name](https://github.com/OpenBagTwo/AngerLocalBeehive/blob/main/notebooks/Wheres%20My%20Mule.ipynb) or [nbt property](https://github.com/OpenBagTwo/AngerLocalBeehive/blob/main/notebooks/The%20Mountain%20Goats.ipynb)
- [Creating a Creative Mode copy of a world](https://github.com/OpenBagTwo/AngerLocalBeehive/blob/main/notebooks/Switching%20Game%20Modes.ipynb)
- [Locating unopened loot chests](https://github.com/OpenBagTwo/AngerLocalBeehive/blob/main/notebooks/Otherside.ipynb)
- [Getting the ore composition of chunklets](https://github.com/OpenBagTwo/AngerLocalBeehive/blob/main/notebooks/Finding%20an%20Iron%20Vein.ipynb)

(TODO: make separate issues for each of these, but they're all blocked by this issue, so...)

### Sub-tasks
- [ ] create package structure (`pip` installation is a must-have, `poetry` would be sugar)
- [ ] research options for auto-versioning that wouldn't bump versions on changes to the notebooks (I think I can do this while keeping everything in one repo using [worktree](https://git-scm.com/docs/git-worktree))
- [ ] set up HTML docs, explicitly to include notebooks (sphinx had a plugin for this, I would be super surprised if mkdocs doesn't have a wrapper for nbconvert as well)
- [ ] unit tests (am I going to need to create a testing world?)
- [ ] CI via github actions
- [ ] onboard to PyPI
- [ ] CD via github actions

**Comment by OpenBagTwo** [comment]
Reminder to self that versioneer isn't compatible with poetry (https://github.com/OpenBagTwo/EnderChest/pull/19).

I could always take this as an opportunity to explore [alternatives](https://pypi.org/project/poetry-dynamic-versioning/)...
